security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
                    entity:
                        class: App:User

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            pattern:    ^/
            provider: our_db_provider
            logout_on_user_change: true

            guard:
                authenticators:
                    - app.security.login_form_authenticator
                    - app.security.social_buttons_authenticator
            entry_point: App\Security\LoginFormAuthenticator

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
#            form_login:
#                login_path: main_page
#                check_path: main_page

            logout:
                path:   /logout
                target: /login

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/admin, roles: ROLE_USER }